#!bin/bash

# Unnecessary files for collecting are deleted from directory $1 to $2 - 1

for ((i=$1; i<$2; i++)); do
    cd $i
    rm -r COSMO
    rm -r MOCOEFS
    rm -r MOLDEN
    rm -r RESTART
    rm *
    cd ..
done
