#!bin/bash

# User input
src=/home-4/yshen57@jhu.edu/data/yshen/Columbus/C5H9O/src # Columbus input template directory
NAtoms=15

# Do the jub
i=0
count=1
while read -r line; do
    if [ $count == 1 ]; then
        if [ ! -d $i ]; then
            mkdir $i
        fi
        cd $i
        cp $src/* .
        echo "$line" > geom
        count=$[count+1]
    elif [ $count == $NAtoms ]; then
        echo "$line" >> geom
        cd ..
        i=$[i+1]
        count=1
    else
        echo "$line" >> geom
        count=$[count+1]
    fi
done < geom.all