#!bin/bash

# Command line input
usage="Submit new Columbus7 job or resubmit failed job

$(basename "$0") [-h] [-s n]

optional arguments:
  -h             show this help message and exit
  -s             queuing system (default = slurm)"

queue='slurm'
while getopts ':hs:' option; do
  case "$option" in
    h) echo "$usage"
       exit;;
    s) queue=$OPTARG;;
    :) printf "missing argument for -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit;;
   \?) printf "illegal option: -%s\n" "$OPTARG" >&2
       echo "$usage" >&2
       exit;;
  esac
done
shift $((OPTIND - 1))

# Do the job
for entry in * ; do
    if [ -d $entry ]; then # This is a directory
        cd $entry
        if [ -f 'geom' ]; then # This is a job directory
            if [ ! -f 'runc.log' ]; then # This is a new job
                cp ../RunColumbus .
                sbatch RunColumbus
            else # This job has started
                success=`cat runc.log |grep timings`
                if [ ! -n "$success" ]; then # This job has not yet succeeded
                    error=`cat runc.log |grep 'Error occured!'`
                    timeout=`cat ${queue}* |grep TIMEOUT`
                    if [ -n "${error}${timeout}" ]; then # This job has failed
                        echo 'Failed job '$entry
                        if [ -d WORK ]; then # Remove Columbus7 scratch
                            rm -r WORK
                        fi
                        rm ${queue}* # Remove queuing system log
                        sbatch RunColumbus
                    fi
                fi
            fi
        fi
        cd ..
    fi
done
